version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
#  adminer:
#    image: adminer:4.7.8-standalone
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
  backend:
    build: ./todo_list
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "
      python manage.py migrate &&
      python manage.py create_users &&
      python manage.py create_projects &&
      python manage.py create_todos &&
      gunicorn todo_list.wsgi -b 0.0.0.0:8080"
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
